### ISSUE TITLE
Hello and Are You?

### ISSUE THREAD

**Issue by silver2row** [wgaonar/BeagleCPP#1]
Hello,

Are you making a new book dedicated to the BBB or other related type SBCs from the beagleboard.org people? If so, awesome! I have been waiting on a new book dedicated to the BBB or other related family boards they produce.

This is me. I am the person that said I would test your library on the BBB and return service. I have been a bit busy lately but I will test this library in one form or another.

Thank you for making this library available.

Seth

P.S. If you are producing a book and have a publisher, please direct me on where I can go online to purchase the ebook copy.

**Comment by wgaonar** [comment]
Hello. Yes, am here. 

In the beginning, it was a hobby, but lately, the idea to write a book started to bounce in my head. My main motivation is that there is not a C++ library available where you can use any sensor or motors, like an object of real life, I mean with methods and attributes like in the OOP paradigm.

By now I have not tried to contact any editor, but you could help me test the library. I can support you in case of any doubts.

**Comment by silver2row** [comment]
@wgaonar ,

Yes sir, I will test soon w/ some sensors and ideas. Backlog is my name these days. I will find time soon. Oh and sorry to get nosy about the editor ideas. 

Seth

P.S. Testing will ensue! Okay, I have tested the build process and workings of the LED functions in Listing_1.1.out so far. I noticed that I needed sudo permissions to handle this library. No issue here. I will keep testing the source. I am ` not ` discrediting your expertise here nor am I harassing you. Nice lib! 

Oh and I cannot wait to make it through until I build them all and use PWM in C/C++ filing systems for the BBGW.

**Comment by silver2row** [comment]
Hello Sir,

@wgaonar , I am receiving an error on the build for Listing_1.2.cpp. I switched out some of the source to try to make for while loops with endings as ` { ` instead of ` ; ` but this did not cure the build process.

For instance, this is the error:

```

Building BeagleBone Application...
/usr/bin/ld: /tmp/ccewrhMy.o: in function `main':
Listing_1.2.cpp:(.text+0x23e): undefined reference to `DelayMilliseconds(int)'
/usr/bin/ld: Listing_1.2.cpp:(.text+0x27a): undefined reference to `DelayMilliseconds(int)'

```

Also, this is the altered source:

```

int count = 0;
  while (count < 10)
  {
    while (buttonPin.DigitalRead() == LOW) {
    count++;
    cout << "The button was pressed, turning the led ON "
          << RainbowText(to_string(count), "Red") << " times" << endl;
    ledPin.DigitalWrite(HIGH);
    }
    while (buttonPin.DigitalRead() == HIGH) {
      DelayMilliseconds(10);
    cout << "The button was released, turning the led OFF" << endl << endl;
    ledPin.DigitalWrite(LOW);
    DelayMilliseconds(10);
    }
  }

```

I thought that while loops ended with ` { ` and not ` ; `. If I am wrong for whatever reason, please let me know.

Seth

P.S. I will go and look in DelayMilliseconds() in the GPIO class.

**Comment by wgaonar** [comment]
Thanks. It was missing a library file in the build file. It should compile now.

**Comment by silver2row** [comment]
@wgaonar ,

Okay. No issue. I can keep testing if necessary. 

Seth

P.S. Good w/ me. Closing now!

**Comment by silver2row** [comment]
Hello,

Just checking back to see if you need anything. I am okay w/ English and can probably point out ` flaws ` in typing or typos if indeed you are going to go through w/ making the book. If and when you think of producing the book, please inform me or I will keep checking back.

Seth

P.S. Is the driver in the DC Motor section to your repo. for the chip on the BBBlue?

**Comment by silver2row** [comment]
Hello Sir,

Seth here. Are you still wanting to promote a book about your findings and knowledge that is dedicated to the am335x and BBB?

Seth

P.S. For one, I would purchase to know a bit of what info. and data you described in the book. Anyway, please let me know if you are interested in making a book. I think this would be a good idea. You seem to know a lot and I always liked the am335x and peripherals listed on the BBB and other related am335x boards. So, when you have time, please let me know. 

Oh! I will be going through the articles like I described a couple months back. I have projects I attend to currently. Some are interesting and others are for fun mostly. I have hoped to see a book in North America or on Amazon about these findings...

**Comment by wgaonar** [comment]
Hello, Yes I am working on the library. I am re-implementing some code portions related to the use of threads. I noted that It could be improved. I am learning about some thread-related stuff.  

What do you think about a virtual meeting for starting to program with the BBB? I can explain to you and your colleagues the basic implementations that I have done, for free, i.e. with no cost.

**Comment by silver2row** [comment]
Hello,

No issue. I am just me. I do not have other people that advise me or control my momentum. 

I am more of a contractor. I find the work that you have done awesome. It is nice to read over the ideas. If you want, we can meet virtually if necessary. I would rather not b/c of me just being me and not having a group of individuals that would be able to benefit from your expertise.

Seth

P.S. I am a full fledged BBB user as of now. I like the am335x and TI based chips. So, I keep on learning. If you want, look at some BBB based ideas from me here: https://github.com/silver2row/BBBW_RELAYCAPE . It is basically GPIO only but for the RelayCape.

**Comment by silver2row** [comment]
```
message = "\nTB6612FNG driver module with the next components / pins was created and activated:\n" +
            std::string("\tMotorA:\n") +
            std::string("\t\tAIN1: ") + this->MotorA.input1Pin.GetPinHeaderId() + "\n" + 
            std::string("\t\tAIN2: ") + this->MotorA.input2Pin.GetPinHeaderId() + "\n" + 
            std::string("\t\tPWMA: ") + this->MotorA.pwmPin.GetPinHeaderId() + "\n" +
            std::string("\t\tSwap Spin: ") + swapStringMotorA + "\n" +
            std::string("\tMotorB:\n") +
            std::string("\t\tBIN1: ") + this->MotorB.input1Pin.GetPinHeaderId() + "\n" + 
            std::string("\t\tBIN2: ") + this->MotorB.input2Pin.GetPinHeaderId() + "\n" + 
            std::string("\t\tPWMB: ") + this->MotorB.pwmPin.GetPinHeaderId() + "\n" +
            std::string("\t\tSwap Spin: ") + swapStringMotorB + "\n" +
            "\n\n";
```

Where does ` GetPinHeaderId() ` come from currently. Is that to control the GPIO and PWM pin muxing on the BBB?

Seth

P.S. Sorry to not want to meet virtually. I really am just a user for now. I have no use case as of now. I am just learning and going along w/ my interests in electronics and programming.

**Comment by wgaonar** [comment]
Hello. Sorry for the delay. I have read your message but I have not answered it. You are right, GetPinHeaderId() comes from GPIO class.
